Removed patching files and reverted .travis.yml.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,18 +8,31 @@ go:
 
 os:
   - linux
+  - linux-ppc64le
+  - linux-s390
 
 services:
   - docker
 
 branches:
   only:
-    - 3.1.2-patch
+    - master
+    - /^[0-9]+\..*$/
+    - /^v[0-9]+\..*$/
+    - /^release-[0-9]+\..*$/
 
 env:
   matrix:
     - OS=rhel7 TARGET=9.42.40.115
     - OS=linux
+
+matrix:
+  fast_finish: true
+  exclude:
+  - os: linux-ppc64le
+    env: OS=rhel7 TARGET=9.42.40.115
+  - os: linux-s390
+    env: OS=rhel7 TARGET=9.42.40.115
 
 before_install:
   - source travis-env.sh
@@ -30,7 +43,25 @@ install:
 before_script:
   - make tunnel
   - make artifactory-login
-  
+  - make lint
+
 script:
   - make image
+  - |
+      if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "s390x" ]]; then
+        make go-verify
+      fi
   - make push-images
+
+after_success:
+  - |
+      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
+        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
+        python travis_after_all.py https://travis.ibm.com/api
+        export $(cat .to_export_back)
+        if [[ "$BUILD_LEADER" == "YES" ]]; then
+          if [[ "$BUILD_AGGREGATE_STATUS" != "others_succeeded" ]]; then
+            echo "Some jobs failed" && exit 1
+          fi
+        fi
+      fi
