Added build elements for when we start using UBI image.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,6 +10,7 @@ os:
   - linux
   - linux-ppc64le
   - linux-s390
+
 services:
   - docker
 
@@ -19,17 +20,10 @@ branches:
 
 env:
   matrix:
-    - OS=rhel7 TARGET=9.42.99.162
     - OS=linux
 
 matrix:
   fast_finish: true
-  exclude:
-  - os: linux-ppc64le
-    env: OS=rhel7 TARGET=9.42.99.162
-  - os: linux-s390
-    env: OS=rhel7 TARGET=9.42.99.162
-
 
 before_install:
   - source travis-env.sh
@@ -40,7 +34,33 @@ install:
 before_script:
   - make tunnel
   - make artifactory-login
+  - make lint
 
 script:
   - make image
+  - |
+      if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "s390x" ]]; then
+        make go-test
+        echo "testing complete"
+        make go-fmt
+        echo "go fmt complete"
+      fi
   - make push-images
+  - |
+      if [[ "$(uname -m)" != "ppc64le" && "$(uname -m)" != "s390x" ]]; then
+        make rhel-images
+      fi
+  
+
+after_success:
+  - |
+      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
+        curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
+        python travis_after_all.py https://travis.ibm.com/api
+        export $(cat .to_export_back)
+        if [[ "$BUILD_LEADER" == "YES" ]]; then
+          if [[ "$BUILD_AGGREGATE_STATUS" != "others_succeeded" ]]; then
+            echo "Some jobs failed" && exit 1
+          fi
+        fi
+      fi
